### ISSUE TITLE
On cancel request

### ISSUE THREAD

**Issue by enoma1** [Sammyskills/codeigniter-paystack-library#1]
If a transaction is canceled it just destroys on the page not returning to the previous page

**Comment by sammyskills** [comment]
By default, when a transaction is cancelled, it returns to the previous page. I just tested it again, to confirm. It doesn't destroy on the page. See attached gif

![2020-08-17 10-38-06](https://user-images.githubusercontent.com/8720569/90382406-9cd21d80-e076-11ea-817d-f4a21965b54e.gif)

**Comment by enoma1** [comment]
Wow, I'll check again thank you. You saved me a lot of stress

**Comment by emmieplus** [comment]
Please, am trying to use this project on my localhost but am have Undefined index: data.

Please, any help
